import Head from 'next/head'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Job Tracker</title>
        <meta name="Job Tracker App for Programmers" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Dashboard Page
      </main>
    </div>
  )
}
