import Head from 'next/head'
import Layout from '../components/layout';

export default function Home() {

  return (
    <Layout page={'home'}>
      <Head>
        <title>Job Tracker</title>
        <meta name="Job Tracker App for Programmers" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        Dashboard Page
      </main>
    </Layout>
  )
}
